# Generated by Django 3.2 on 2023-04-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_favorite_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='foods',
            new_name='products',
        ),
    ]
